// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTubeDownloader.Contexts;

#nullable disable

namespace YouTubeDownloader.Migrations
{
    [DbContext(typeof(SongsDbContext))]
    [Migration("20220331165822_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");
#pragma warning restore 612, 618
        }
    }
}
